### ISSUE TITLE
Supports Aseprite v1.3?

### ISSUE THREAD

**Issue by redactedscribe** [eddex/aseprite-windows-docker-build#12]
IIRC, the build process took quite some time, so instead of trying it myself, I'm curious whether this script works with the new [Aseprite v1.3](https://github.com/aseprite/aseprite/releases/tag/v1.3)?

Thanks.

**Comment by eddex** [comment]
I just updated the script to build v1.3 by default. You can change to any version by updating the version in `build.bat`:
https://github.com/eddex/aseprite-windows-docker-build/blob/75a52bbeb768c25145811fd9647cb96933c9e019/build.bat#L19

You can find the full list of Aseprite versions here: https://github.com/aseprite/aseprite/tags
