### ISSUE TITLE
Unknown download location

### ISSUE THREAD

**Issue by CornisPopped** [eddex/aseprite-windows-docker-build#13]
Hi, I'm new to this, but I downloaded Docker and the zip, and then ran the start.bat
I left my computer running and now when I come back, I don't find a bin/ anywhere. The command prompt closed on its own, and I am not sure where I can find the files. I know they exist on my PC now because my C: drive is down ~10GB.

**Comment by eddex** [comment]
Hi
Thanks for reaching out, can you see any kind of error message? Are you sure you use Windows containers and not Linux containers?

**Comment by CornisPopped** [comment]
Hello, 
Sorry for the late reply! I did not see any kind of error messages, but it looks like the space magically reclaimed itself. Sorry I can't be of much assistance in debugging it!

**Comment by eddex** [comment]
You could try to open a CMD window, navigate to to the folder where you downloaded the repo and run `start.bat` from within CMD. This way you should see any errors.

I will close this for now, feel free to come back if you want further assistance,
