### ISSUE TITLE
"Unable to find image" error

### ISSUE THREAD

**Issue by Zeperox** [eddex/aseprite-windows-docker-build#18]
![image](https://github.com/eddex/aseprite-windows-docker-build/assets/53876273/347811e5-ec8d-4571-9355-95a7c88b1400)
I have no clue what is going on (I do not know anything about Docker or what I assume is CMake), all I know is that this error appears every time I attempt to run the batch file

**Comment by djkouza** [comment]
Getting the same issue. Seems to stem from:

FROM abrarov/msvc-2022:2.15.0
failed to register layer: link /Files/Program Files/common files/Microsoft Shared/Ink/en-US/micaut.dll.mui /Files/Program Files (x86)/common files/Microsoft Shared/ink/en-US/micaut.dll.mui: no such file or directory

So the build fails and then everything else fails after.

**Comment by djkouza** [comment]
So I had this same error, but found out my drive was full. 
Check #1 you have enough space to d/l all the required files
#2 make sure you are in Windows Container mode per the read me.

**Comment by eddex** [comment]
Closing this. Thanks @djkouza for the help. I'll add this to the README.
