### ISSUE TITLE
The system cannot find the file specified.

### ISSUE THREAD

**Issue by Excalidoom** [eddex/aseprite-windows-docker-build#4]
Error response from daemon: open \\.\pipe\docker_engine_windows: The system cannot find the file specified."

I keep getting this after switching to Windows Containers.

If I stick on linux, It works until it has to do a link that fails. 

I've tried clean vers multiple times, same thing

**Comment by eddex** [comment]
Seems to be an issue with the latest version of Docker for Windows.

You may need to enable the “Microsoft-Hyper-V” and the “Containers” feature in Windows.

Open **PowerShell as Administrator** and execute the following command:
```ps
Enable-WindowsOptionalFeature -Online -FeatureName $("Microsoft-Hyper-V", "Containers") -All
```

Hope this helps :)

Source: https://forums.docker.com/t/error-response-from-daemon-open-pipe-docker-engine-windows-the-system-cannot-find-the-file-specified/131750/9
